const mongoose=require('mongoose')
const userSchema=new mongoose.Schema({
    username:{
        type:String,
        require:true
    },
    email:{
        type:String,
        require:true
    },
    password:{
        type:String,
        require:true
    },
    followers:[
       {
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
       }
    ],
    following:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        }
    ],
    posts:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Post'
        }
    ],
    reels:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Reel'
        }
    ],
    followRequests:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        }
    ],
    image:{
        type:String,
        require:true
    },
    myRequests:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        }
    ],
    notification:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Notification'
        }
    ]
},{timestamps:true})

module.exports=mongoose.model("User",userSchema)